@startuml


獨居老人通報人員 -> 獨居老人縣府承辦: 通報審核中
獨居老人縣府承辦 -> 獨居老人社工: 建檔(獨居老人管理)
獨居老人縣府承辦 --[#red]>獨居老人通報人員: 結案


' 獨居老人社工 -> 獨居老人委外單位主管:查核中
' 獨居老人委外單位主管 -> 獨居老人縣府承辦:複核中
' 獨居老人公所承辦 -> 

' 主責社工 -> 督導: 督導審核中
' 督導 --> 派案社工:
' 督導 -->主責社工: 退件
' 督導 -> 主管科長 : 科長/主管審核中
' 主管科長 --[#red]>主責社工:退件
' 主管科長->主責社工:主責處遇中
' 主責社工 -> 主責社工:主責送結案
' 主責社工-> 歸檔:歸檔
' 歸檔-->主責社工:退件

@enduml
