@startuml

通報人員 -> 縣府承辦:申請中

通報人員 <- 縣府承辦:抽回
縣府承辦 -> 
' 派案社工 -> 中心督導: 篩派案中
' 中心督導 --> 派案社工: 退件

' 中心督導 -> 主責社工: 主責處遇中
' 主責社工 -> 督導: 督導審核中
' 督導 -->主責社工: 退件
' 督導 -> 主管科長 : 科長/主管審核中
' 主管科長 --[#red]>主責社工:退件
' 主管科長->主責社工:主責處遇中
' 主管科長->主責社工:主責個管中

' 主責社工 -> 主責社工:主責送結案

' 主責社工-> 歸檔:歸檔
' 歸檔-->主責社工:退件
@enduml