@startuml

start
:判斷i是否具有權限;
if (i == true) then (yes)
  :顯示功能;
  :具有新增、停用、檢視功能;

  :【新增】建立【據點單位名稱、統一編號】;
  :設定對應的【鄉鎮市、村里】;
  if (新增【村里】) then (yes)
    :驗證該村里未被其他關懷據點綁定;
    if (驗證通過) then (yes)
      :新增該村里;
    else (no)
      :不新增該村里;
    endif
  endif

  :【檢視】修改對應的【村里】;
  if (【村里】被刪除) then (yes)
    :其他關懷據點可選擇該【村里】;
  endif

  :【新增人員】撈取所有【SINGLE_ELDER_CAREPERSON】角色;
  :新增選擇人員;
  :該人員綁定該單位;

  :【檢視】修改對應的人員帳號;

else (no)
  :隱藏功能;
endif
stop
@enduml
