@startuml

start

if (通報狀態 == 4) then (是)
  if (通報判斷 == 重覆通報) then (是)
    :審核按鈕為：歸檔並結案;
    :【通報狀態】 = 6;
  elseif (通報判斷 == 案件重新導入) then (是)
    :審核按鈕：解除舊案並結案;
    :於「獨居老人管理」中將該案件狀態改為【未結案】;
    :【通報狀態】 = 7;
  else (通報判斷 == 新案件待審核) then (是)
    :審核按鈕：通報派案;

    :將通報資訊複製至「獨居老人管理」個案資料;
    :新取獨居老人案件編號;
    :產生初訪表資訊;
    :【通報狀態】 = 5;
  endif
else (通報狀態 == 5 || 通報狀態 == 6 || 通報狀態 == 7 )
  :無審核按鈕;
endif
:通報結束;
stop


note right
  1 通報建檔(status=1)
  2 通報中(status=2)
  3 案件抽回(status=3)
  4 通報審核(status=4)
  5 通報通過(status=5)
  6 重覆通報(status=6)
  7 舊案轉入(status=7)
end note

@enduml
