@startuml

skinparam BackgroundColor #ffffee
scale 600 width

skinparam actor {
  BackgroundColor<<Admin>> LightBlue
  BackgroundColor<<COUNTRY_MANAGER>> Yellow
  BackgroundColor<<SINGLE_ELDER_COUNTY_SUPERVISOR>> DarkBlue
  BackgroundColor<<SINGLE_ELDER_NOTIFIER>> Purple
}

skinparam usecase {
  ArrowColor<<External>> DarkGreen
}

left to right direction

actor 系統管理者<<Admin>>
actor 縣府管理者<<COUNTRY_MANAGER>>
actor 獨居老人訪視縣府承辦<<SINGLE_ELDER_COUNTY_MANAGER>>
actor 獨居老人訪視縣府督導<<SINGLE_ELDER_COUNTY_SUPERVISOR>>
actor 獨居老人委外單位主管<<SINGLE_ELDER_UNIT_MANAGER>>

rectangle 續訪審核作業(含批次) {


  usecase VISIT as "委外主管續訪審核
  AfterElderVisit.appStatus -> SysConfig = (no_)VISIT"
  usecase UNIT_REJECT as "委外主管續訪退件
  AfterElderVisit.appStatus -> SysConfig = (no_)UNIT_REJECT"
  usecase QUERY as "查詢"
  usecase UPDATE as "修改"
  usecase REVIEW as "縣府承辦續訪審核
  AfterElderVisit.appStatus -> SysConfig = (no_)REVIEW"
  usecase COUNTY_REJECT as "縣府承辦續訪退件
  AfterElderVisit.appStatus -> SysConfig = (no_)COUNTY_REJECT"
  usecase CONTINUE_VISIT as "持續訪視
  AfterElderVisit.appStatus -> SysConfig = (no_)CONTINUE_VISIT"
  usecase END as "結案
  AfterElderVisit.appStatus -> SysConfig = (no_)END"

  QUERY <-UP- 獨居老人委外單位主管
  UPDATE <-UP- 獨居老人委外單位主管
  VISIT <-UP- 獨居老人委外單位主管
  UNIT_REJECT <-UP- 獨居老人委外單位主管
  
  QUERY <-- 獨居老人訪視縣府承辦
  UPDATE <-- 獨居老人訪視縣府承辦
  REVIEW <-- 獨居老人訪視縣府承辦
  COUNTY_REJECT <-- 獨居老人訪視縣府承辦
  CONTINUE_VISIT <-- 獨居老人訪視縣府承辦
  END <-- 獨居老人訪視縣府承辦

  縣府管理者 <-- 系統管理者
  獨居老人訪視縣府承辦 <-- 獨居老人訪視縣府督導
  獨居老人訪視縣府承辦 <-- 縣府管理者


}

@enduml
